# Generated by Django 5.2.8 on 2025-11-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='Category',
            new_name='product_category',
        ),
    ]
