# Generated by Django 5.2.8 on 2025-11-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_category_productsmodel_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='product_category',
            new_name='Category',
        ),
    ]
