# Generated by Django 5.2.8 on 2025-11-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_product_category_productsmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='Category',
            new_name='product_category',
        ),
    ]
