# Generated by Django 5.2.8 on 2025-11-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_category_productsmodel_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='offer',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='trending',
            field=models.BooleanField(default=0),
        ),
    ]
