# Generated by Django 5.2.8 on 2026-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_cartmodel_host_cartmodel_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_image',
            field=models.URLField(),
        ),
    ]
