# Generated by Django 5.2.8 on 2026-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_productsmodel_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='product_category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='products_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='products_name',
            field=models.CharField(max_length=200),
        ),
    ]
